### ISSUE TITLE
Change Numbers to Odd - Problem description doesn't match test cases.

### ISSUE THREAD

**Issue by kingparra** [rmotr-curriculum/itp-class#27]
The problem description for the Control Flow > Change Numbers to Odd assignment [here](https://github.com/rmotr-curriculum/itp-class/blob/master/unit-3-control-flow/lesson-3-change-number-to-odd/README.md) is...

> Define a function make_number_odd that receives a number, adds 1 to that 
number if it is even, and returns the number.

...but the test cases require you to also return the number when it's odd. The problem description should be updated to reflect this fact. Adding...

> If the number is odd, return the number.

..to the end should do the trick.

**Comment by santiagobasulto** [comment]
Thanks very much @kingparra, I've just fixed it.
