### ISSUE TITLE
Problem description in 'Create counting list' does not match test case

### ISSUE THREAD

**Issue by kingparra** [rmotr-curriculum/itp-class#28]
In the problem description for the 'Create counting list' assignment [here](https://github.com/rmotr-curriculum/itp-class/tree/24ac899a1464bb2f691b012cd945c86fd0a7b454/unit-3-control-flow/lesson-17-create-counting-list), you're asked to create a list of number counting up to the passed in argument, *starting with zero*. In the test cases, however, the expected result is a list of numbers starting with one.

Changing..

> Return a list where each element counts up to the number provided starting from 0.

..to..

> Return a list where each element counts up to the number provided starting from 1.

in the problem description would fix this.

**Comment by santiagobasulto** [comment]
Fixed! Thanks @kingparra
